version: '3'


services:
    api:
      build: ./api
      ports:
        - '81:81'
      command: bash -c "python3 my_api/manage.py migrate && python3 my_api/manage.py collectstatic --noinput && gunicorn --chdir my_api --bind unix:/home/code/my_api/my_api.sock my_api.wsgi"
